# Generated by Django 5.2 on 2025-05-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainKW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPaaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_kw', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('main_kw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mainkw')),
            ],
        ),
    ]
